-   id: nomerge
    name: nomerge
    entry: nomerge
    require_serial: true
    language: python
    language_version: python3
    types_or: [cython, pyi, python]
    minimum_pre_commit_version: '2.9.2'
